// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountGroupController from "./account_group_controller"
application.register("account-group", AccountGroupController)

import DeleteConfirmController from "./delete_confirm_controller"
application.register("delete-confirm", DeleteConfirmController)

import AutoLinkToggleController from "./auto_link_toggle_controller"
application.register("auto-link-toggle", AutoLinkToggleController)

import BankAccountFormController from "./bank_account_form_controller"
application.register("bank-account-form", BankAccountFormController)

import BankAccountSelectorController from "./bank_account_selector_controller"
application.register("bank-account-selector", BankAccountSelectorController)

import BaseFormController from "./base_form_controller"
application.register("base-form", BaseFormController)

import CategoryFormController from "./category_form_controller"
application.register("category-form", CategoryFormController)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import ContributionModeController from "./contribution_mode_controller"
application.register("contribution-mode", ContributionModeController)

import CurrencyInputController from "./currency_input_controller"
application.register("currency-input", CurrencyInputController)

import DashboardChartsController from "./dashboard_charts_controller"
application.register("dashboard-charts", DashboardChartsController)

import LegalConsentController from "./legal_consent_controller"
application.register("legal-consent", LegalConsentController)

import DebtAdvancedSettingsController from "./debt_advanced_settings_controller"
application.register("debt-advanced-settings", DebtAdvancedSettingsController)

import DebtCalculationSettingsController from "./debt_calculation_settings_controller"
application.register("debt-calculation-settings", DebtCalculationSettingsController)

import DebtFormController from "./debt_form_controller"
application.register("debt-form", DebtFormController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FabMenuController from "./fab_menu_controller"
application.register("fab-menu", FabMenuController)

import FilterDrawerController from "./filter_drawer_controller"
application.register("filter-drawer", FilterDrawerController)

import FilterPanelController from "./filter_panel_controller"
application.register("filter-panel", FilterPanelController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GoalCalculationSettingsController from "./goal_calculation_settings_controller"
application.register("goal-calculation-settings", GoalCalculationSettingsController)

import GoalFormController from "./goal_form_controller"
application.register("goal-form", GoalFormController)

import GoalSelectorController from "./goal_selector_controller"
application.register("goal-selector", GoalSelectorController)

import IconPickerController from "./icon_picker_controller"
application.register("icon-picker", IconPickerController)

import InlineCategoryController from "./inline_category_controller"
application.register("inline-category", InlineCategoryController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import LanguageSwitcherController from "./language_switcher_controller"
application.register("language-switcher", LanguageSwitcherController)

import MobileCarouselController from "./mobile_carousel_controller"
application.register("mobile-carousel", MobileCarouselController)

import MobileDashboardController from "./mobile_dashboard_controller"
application.register("mobile-dashboard", MobileDashboardController)

import MobileFabController from "./mobile_fab_controller"
application.register("mobile-fab", MobileFabController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import MobilePerformanceController from "./mobile_performance_controller"
application.register("mobile-performance", MobilePerformanceController)

import MobileTouchController from "./mobile_touch_controller"
application.register("mobile-touch", MobileTouchController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MotivationalQuotesController from "./motivational_quotes_controller"
application.register("motivational-quotes", MotivationalQuotesController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import NavDropdownController from "./nav_dropdown_controller"
application.register("nav-dropdown", NavDropdownController)

import PageTransitionController from "./page_transition_controller"
application.register("page-transition", PageTransitionController)

import PaymentModeController from "./payment_mode_controller"
application.register("payment-mode", PaymentModeController)

import SavingCalculationSettingsController from "./saving_calculation_settings_controller"
application.register("saving-calculation-settings", SavingCalculationSettingsController)

import SavingFormController from "./saving_form_controller"
application.register("saving-form", SavingFormController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import StatementFilePollingController from "./statement_file_polling_controller"
application.register("statement-file-polling", StatementFilePollingController)

import StatementUploadController from "./statement_upload_controller"
application.register("statement-upload", StatementUploadController)

import TransactionEditController from "./transaction_edit_controller"
application.register("transaction-edit", TransactionEditController)

import TransactionFormController from "./transaction_form_controller"
application.register("transaction-form", TransactionFormController)

import TransactionsFilterController from "./transactions_filter_controller"
application.register("transactions-filter", TransactionsFilterController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import DateRangeController from "./date_range_controller"
application.register("date-range", DateRangeController)

import RowLinkController from "./row_link_controller"
application.register("row-link", RowLinkController)

import DragScrollController from "./drag_scroll_controller"
application.register("drag-scroll", DragScrollController)

import ToggleActiveController from "./toggle_active_controller"
application.register("toggle-active", ToggleActiveController)

import TogglePanelController from "./toggle_panel_controller"
application.register("toggle-panel", TogglePanelController)

import RuleRowController from "./rule_row_controller"
application.register("rule-row", RuleRowController)

import TransactionRowController from "./transaction_row_controller"
application.register("transaction-row", TransactionRowController)

import TransferCandidatesController from "./transfer_candidates_controller"
application.register("transfer-candidates", TransferCandidatesController)

import MerchantSuggestController from "./merchant_suggest_controller"
application.register("merchant-suggest", MerchantSuggestController)

import ReportDownloadController from "./report_download_controller"
application.register("report-download", ReportDownloadController)

import AiInputController from "./ai_input_controller"
application.register("ai-input", AiInputController)

import RecurringSuggestionsController from "./recurring_suggestions_controller"
application.register("recurring-suggestions", RecurringSuggestionsController)

import WebPushController from "./web_push_controller"
application.register("web-push", WebPushController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)
