// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardChartsController from "./dashboard_charts_controller"
application.register("dashboard-charts", DashboardChartsController)

import LanguageSwitcherController from "./language_switcher_controller"
application.register("language-switcher", LanguageSwitcherController)

import SessionTimeoutController from "./session_timeout_controller"
application.register("session-timeout", SessionTimeoutController)

import MotivationalQuotesController from "./motivational_quotes_controller"
application.register("motivational-quotes", MotivationalQuotesController)

import MobileDashboardController from "./mobile_dashboard_controller"
application.register("mobile-dashboard", MobileDashboardController)

import MobileFabController from "./mobile_fab_controller"
application.register("mobile-fab", MobileFabController)

import MobileTouchController from "./mobile_touch_controller"
application.register("mobile-touch", MobileTouchController)

import MobilePerformanceController from "./mobile_performance_controller"
application.register("mobile-performance", MobilePerformanceController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FabMenuController from "./fab_menu_controller"
application.register("fab-menu", FabMenuController)

import MobileCarouselController from "./mobile_carousel_controller"
application.register("mobile-carousel", MobileCarouselController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import FilterDrawerController from "./filter_drawer_controller"
application.register("filter-drawer", FilterDrawerController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import IconPickerController from "./icon_picker_controller"
application.register("icon-picker", IconPickerController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import CategoryFormController from "./category_form_controller"
application.register("category-form", CategoryFormController)
