examples:
  - text: "03/01/2025 Pago Nómina EMPRESA SA 15,000.00"
    expected:
      date: "2025-01-03"
      description: "Pago Nómina EMPRESA SA"
      amount: 15000.00
      transaction_type: "income"
      bank_entry_type: "credit"
      category: "Income"
      sub_category: "Salary"
  - text: "05/01/2025 OXXO Compra -89.00"
    expected:
      date: "2025-01-05"
      description: "OXXO Compra"
      amount: -89.00
      transaction_type: "variable_expense"
      bank_entry_type: "debit"
      category: "Food"
      sub_category: "Snacks"
  - text: "07/01/2025 Netflix -199.00"
    expected:
      date: "2025-01-07"
      description: "Netflix"
      amount: -199.00
      transaction_type: "fixed_expense"
      bank_entry_type: "debit"
      category: "Entertainment"
      sub_category: "Streaming"
